# Learning NumPy
It is a Python library used for working with arrays. NumPy stands for "Numerical Python".

## Why we use NumPy?
Because lists are slow! So we use arrays.

# Installation of NumPy

In [2]:
import numpy as np

# Creating arrays
The array object in NumPy is called `ndarray`. We can create a NumPy `ndarray` object by using the `array()` function.

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


We can pass a list, a tuple or any array-like object into the `array()` method, and it will be converted into an `ndarray`

In [4]:
ex1 = np.array((1, 2, 3, 4, 5, 6, 7))
print(ex1)

[1 2 3 4 5 6 7]


## Dimensions in arrays
A dimension in arrays is one level of array depth.

### 0-D Arrays

In [5]:
zerod_array = np.array(42)
print(zerod_array)

42


### 1-D Arrays

In [6]:
oned_array = np.array([1, 2, 3, 4, 5])
print(oned_array)

[1 2 3 4 5]


### 2-D Arrays

In [7]:
twod_array = np.array([[1, 2], [3, 4]])
print(twod_array)

[[1 2]
 [3 4]]


## Check number of dimensions
The attribute `ndim` returns an integer that tells us how many dimensions the array have.

In [8]:
print(zerod_array.ndim)
print(oned_array.ndim)
print(twod_array.ndim)

0
1
2


## Higher dimensional arrays
When creating an array, we can define the dimension using `ndmin` inside the `array()`function.

In [9]:
higher_da = np.array([1, 2, 3, 4], ndmin=5)
print(higher_da.ndim)

5


# Indexing
An array element can be accessed by referring to its index number. 

## Access 2-D arrays
To do this, we can use comma separated integers representing the `dimension` and the `index of the element`.

In [10]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr.ndim)
print(arr[1, 0])

2
6


## Access 3-D arrays

In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


# Slicing
This works as a in regular Python:
- [start:end]
- [start:end:step]

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:4])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [13]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2[1, 1:4])
print(arr2[0, 0:2])
print(arr2[0:2, 2])
print(arr2[0:2, 1:4])

[7 8 9]
[1 2]
[3 8]
[[2 3 4]
 [7 8 9]]


# Data Types
NumPy has some extra data types, and we refer to data types with one character:
- i, integer
- b, boolean
- u, unsigned integer
- f, float
- c, complex float
- O, object
- S, string

In order to check the data type of an array, the NumPy array object has a property called `dtype` that returns the data type of an array.

In [15]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr2 = np.array(['apple', 'banana', 'cherry'])
print(arr2.dtype)

int32
<U6


## Creating arrays with a defiend data typw
The function `array()` can take an additional argument to set the data type (`dtype=`).

In [16]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## Converting data type on existing arrays
The best way to change the data type of an existing array is to make a copy of the array with the `astype()` method.

In [25]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype("i")
print(arr.dtype)
print(newarr.dtype)

float64
int32
