# Learning NumPy
It is a Python library used for working with arrays. NumPy stands for "Numerical Python".

## Why we use NumPy?
Because lists are slow! So we use arrays.

# Installation of NumPy

In [36]:
import numpy as np

# Creating arrays
The array object in NumPy is called `ndarray`. We can create a NumPy `ndarray` object by using the `array()` function.

In [37]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


We can pass a list, a tuple or any array-like object into the `array()` method, and it will be converted into an `ndarray`

In [38]:
ex1 = np.array((1, 2, 3, 4, 5, 6, 7))
print(ex1)

[1 2 3 4 5 6 7]


## Dimensions in arrays
A dimension in arrays is one level of array depth.

### 0-D Arrays

In [39]:
zerod_array = np.array(42)
print(zerod_array)

42


### 1-D Arrays

In [40]:
oned_array = np.array([1, 2, 3, 4, 5])
print(oned_array)

[1 2 3 4 5]


### 2-D Arrays

In [41]:
twod_array = np.array([[1, 2], [3, 4]])
print(twod_array)

[[1 2]
 [3 4]]


## Check number of dimensions
The attribute `ndim` returns an integer that tells us how many dimensions the array have.

In [42]:
print(zerod_array.ndim)
print(oned_array.ndim)
print(twod_array.ndim)

0
1
2


## Higher dimensional arrays
When creating an array, we can define the dimension using `ndmin` inside the `array()`function.

In [62]:
higher_da = np.array([1, 2, 3, 4], ndmin=5)
print(higher_da.ndim)

5


# Indexing
An array element can be accessed by referring to its index number. 

## Access 2-D arrays
To do this, we can use comma separated integers representing the `dimension` and the `index of the element`.

In [44]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr.ndim)
print(arr[1, 0])

2
6


## Access 3-D arrays

In [63]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

12


# Slicing
This works as a in regular Python:
- [start:end]
- [start:end:step]

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:4])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [47]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2[1, 1:4])
print(arr2[0, 0:2])
print(arr2[0:2, 2])
print(arr2[0:2, 1:4])

[7 8 9]
[1 2]
[3 8]
[[2 3 4]
 [7 8 9]]


# Data Types
NumPy has some extra data types, and we refer to data types with one character:
- i, integer
- b, boolean
- u, unsigned integer
- f, float
- c, complex float
- O, object
- S, string

In order to check the data type of an array, the NumPy array object has a property called `dtype` that returns the data type of an array.

In [48]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr2 = np.array(['apple', 'banana', 'cherry'])
print(arr2.dtype)

int32
<U6


## Creating arrays with a defiend data typw
The function `array()` can take an additional argument to set the data type (`dtype=`).

In [49]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## Converting data type on existing arrays
The best way to change the data type of an existing array is to make a copy of the array with the `astype()` method.

In [50]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype("i")
print(arr.dtype)
print(newarr.dtype)

float64
int32


# Array Copy vs View
- `copy`: a new array. It owns the data and any changes to the copy will not affect original array, and any changes made to the original array will not affect the copy.
- `view`: a view of the original array. It does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [51]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [52]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[42  2  3  4  5]


## Check if array owns its data
Every array has the attribute `base` that returns `None` if the array owns the data.

In [53]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base) 

None
[1 2 3 4 5]


# Array shape
The shape of an array is the number of elements in each dimension. NumPy arrays have the attribute `shape` that returns a tuple ith each index having the number of corresponding elements.

In [54]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape) # there are two dimensions, and each has 4 elements

(2, 4)


In [55]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


# Array reshaping
Reshaping means changing the shape of an array. With this we can add or remove dimensions or change number of elements in each dimension.

## Reshape from 1-D to 2-D

In [56]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3) # 4 arrays, each with 3 elements

print(newarr)
print(newarr.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


## Reshape from 1-D to 3-D

In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2) # 2 arrays that contain 3 arrays, each with 2

print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

## Flattening the arrays
This means converting a multidimensional array into a 1D array. This is done using the command `reshape(-1)`

In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)

print(arr)
print(newarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
